# Generated by Django 2.1.7 on 2019-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=15)),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=200)),
                ('plot', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('awards', models.CharField(max_length=20)),
                ('poster', models.CharField(max_length=250)),
                ('ratings', models.CharField(max_length=500)),
                ('metascore', models.CharField(max_length=5)),
                ('imdbRating', models.CharField(max_length=5)),
                ('imdbVotes', models.CharField(max_length=10)),
                ('imdbD', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('totalSeasons', models.CharField(max_length=5)),
                ('dvd', models.CharField(max_length=15)),
                ('boxOffice', models.CharField(max_length=15)),
                ('Production', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=250)),
            ],
        ),
    ]
