# Generated by Django 2.1.7 on 2019-03-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbD',
            new_name='imdbID',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Production',
            new_name='production',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Website',
            new_name='website',
        ),
    ]
